// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: marker.sql

package models

import (
	"context"
)

const getMarkerByBlockID = `-- name: GetMarkerByBlockID :one
SELECT
  block_id, created_at, updated_at, deleted_at
FROM
  markers
WHERE
  block_id = $1
`

func (q *Queries) GetMarkerByBlockID(ctx context.Context, blockID string) (*Marker, error) {
	row := q.db.QueryRowContext(ctx, getMarkerByBlockID, blockID)
	var i Marker
	err := row.Scan(
		&i.BlockID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const markBlock = `-- name: MarkBlock :exec
INSERT INTO
  markers (block_id)
VALUES
  ($1) RETURNING block_id, created_at, updated_at, deleted_at
`

func (q *Queries) MarkBlock(ctx context.Context, blockID string) error {
	_, err := q.db.ExecContext(ctx, markBlock, blockID)
	return err
}
