// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package models

import (
	"database/sql"
)

type Block struct {
	ID        string        `db:"id" json:"id"`
	Data      []int32       `db:"data" json:"data"`
	Height    sql.NullInt32 `db:"height" json:"height"`
	CreatedAt sql.NullTime  `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime  `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime  `db:"deleted_at" json:"deleted_at"`
}

type Marker struct {
	BlockID   string       `db:"block_id" json:"block_id"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type Node struct {
	ID        string       `db:"id" json:"id"`
	Address   string       `db:"address" json:"address"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
}
